CREATE TABLE IF NOT EXISTS mytable(
   drink_id  INTEGER  NOT NULL PRIMARY KEY 
  ,size      VARCHAR(1) NOT NULL
  ,sugar_lvl VARCHAR(4) NOT NULL
  ,ice_lvl   VARCHAR(9) NOT NULL
  ,price     VARCHAR(5) NOT NULL
  ,order_id  INTEGER  NOT NULL
);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (1,'S','100%','light ice','$5.84',136);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (2,'S','100%','regular','$6.40',32);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (3,'M','100%','regular','$5.94',78);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (4,'S','0%','light ice','$5.71',125);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (5,'S','70%','light ice','$5.82',55);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (6,'S','0%','regular','$5.46',173);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (7,'M','50%','light ice','$6.86',70);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (8,'L','30%','no ice','$7.94',163);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (9,'S','30%','no ice','$6.39',7);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (10,'L','0%','regular','$5.17',171);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (11,'S','0%','regular','$8.11',6);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (12,'M','30%','light ice','$6.60',31);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (13,'L','0%','regular','$7.66',10);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (14,'L','50%','regular','$6.63',50);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (15,'L','30%','no ice','$8.77',140);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (16,'M','70%','light ice','$8.47',160);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (17,'S','100%','regular','$6.54',75);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (18,'L','50%','no ice','$5.21',118);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (19,'M','70%','regular','$8.79',184);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (20,'L','70%','regular','$6.73',51);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (21,'S','50%','regular','$7.11',133);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (22,'M','30%','no ice','$5.09',115);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (23,'M','100%','light ice','$6.70',146);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (24,'M','100%','regular','$6.47',116);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (25,'S','50%','light ice','$7.09',120);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (26,'L','70%','regular','$6.81',135);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (27,'M','100%','no ice','$5.61',67);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (28,'S','100%','regular','$6.89',38);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (29,'S','50%','regular','$7.01',171);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (30,'L','0%','light ice','$5.13',108);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (31,'L','100%','light ice','$7.41',17);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (32,'S','100%','light ice','$8.23',14);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (33,'S','100%','light ice','$7.27',147);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (34,'S','100%','no ice','$6.86',52);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (35,'L','50%','no ice','$6.79',109);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (36,'L','50%','light ice','$7.17',48);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (37,'S','50%','light ice','$8.45',10);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (38,'M','0%','light ice','$8.47',112);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (39,'L','50%','light ice','$8.53',193);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (40,'S','100%','no ice','$5.00',174);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (41,'M','30%','no ice','$5.33',64);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (42,'S','50%','no ice','$8.81',59);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (43,'L','0%','regular','$6.60',11);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (44,'L','100%','regular','$8.71',78);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (45,'S','50%','light ice','$6.66',197);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (46,'M','0%','no ice','$5.53',43);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (47,'L','30%','no ice','$7.57',92);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (48,'L','50%','no ice','$6.55',104);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (49,'S','0%','light ice','$5.56',129);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (50,'L','0%','no ice','$7.57',86);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (51,'S','50%','light ice','$5.10',57);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (52,'M','70%','regular','$7.94',27);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (53,'S','50%','regular','$5.25',177);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (54,'L','100%','regular','$7.88',174);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (55,'S','50%','no ice','$8.98',124);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (56,'M','0%','no ice','$8.26',92);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (57,'M','30%','no ice','$6.44',137);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (58,'M','100%','regular','$5.00',196);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (59,'M','50%','light ice','$6.63',120);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (60,'S','50%','light ice','$8.75',4);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (61,'M','100%','regular','$8.99',178);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (62,'L','100%','regular','$8.86',131);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (63,'L','100%','no ice','$6.83',83);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (64,'M','0%','regular','$7.04',66);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (65,'M','50%','regular','$5.16',54);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (66,'S','70%','no ice','$7.40',100);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (67,'M','50%','regular','$5.63',152);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (68,'L','70%','no ice','$5.13',49);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (69,'S','100%','no ice','$7.90',41);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (70,'M','100%','no ice','$8.37',142);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (71,'S','50%','no ice','$7.57',51);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (72,'S','50%','no ice','$6.37',164);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (73,'S','50%','no ice','$7.75',37);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (74,'S','30%','light ice','$6.73',45);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (75,'M','30%','light ice','$8.09',50);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (76,'S','70%','no ice','$8.08',144);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (77,'L','50%','light ice','$8.56',134);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (78,'M','0%','no ice','$7.04',45);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (79,'L','50%','no ice','$8.07',99);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (80,'M','100%','light ice','$7.01',50);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (81,'S','30%','no ice','$6.74',169);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (82,'L','70%','regular','$8.34',72);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (83,'L','70%','regular','$5.44',25);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (84,'M','70%','no ice','$5.65',1);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (85,'M','30%','no ice','$7.05',80);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (86,'M','0%','no ice','$6.46',176);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (87,'S','30%','regular','$5.67',74);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (88,'M','0%','regular','$5.91',7);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (89,'M','50%','no ice','$6.98',11);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (90,'M','0%','light ice','$8.58',140);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (91,'M','30%','light ice','$6.98',90);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (92,'S','0%','light ice','$8.39',147);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (93,'L','30%','no ice','$5.38',26);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (94,'M','70%','no ice','$8.98',199);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (95,'L','30%','no ice','$8.63',59);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (96,'S','50%','no ice','$5.67',101);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (97,'M','50%','no ice','$5.70',44);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (98,'M','30%','no ice','$8.78',182);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (99,'L','100%','regular','$7.16',63);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (100,'M','50%','regular','$8.52',77);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (101,'M','100%','light ice','$6.67',88);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (102,'M','70%','light ice','$7.70',21);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (103,'S','70%','no ice','$7.92',100);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (104,'M','100%','light ice','$7.41',81);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (105,'L','30%','no ice','$7.79',98);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (106,'L','100%','no ice','$7.66',69);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (107,'M','70%','light ice','$7.10',5);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (108,'L','30%','regular','$8.39',36);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (109,'S','30%','light ice','$8.41',133);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (110,'L','70%','no ice','$5.63',113);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (111,'L','50%','regular','$5.15',51);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (112,'S','70%','no ice','$8.21',117);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (113,'S','70%','regular','$5.58',155);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (114,'M','70%','regular','$7.25',39);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (115,'L','70%','regular','$5.28',99);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (116,'S','70%','no ice','$8.81',156);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (117,'M','70%','no ice','$7.21',84);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (118,'L','30%','regular','$8.83',110);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (119,'M','50%','regular','$7.68',131);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (120,'S','30%','light ice','$5.28',149);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (121,'S','70%','light ice','$7.46',33);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (122,'M','30%','regular','$6.26',2);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (123,'L','30%','no ice','$6.54',163);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (124,'L','70%','no ice','$7.89',52);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (125,'L','70%','no ice','$5.00',130);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (126,'S','0%','regular','$8.95',145);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (127,'M','0%','regular','$7.55',131);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (128,'M','70%','light ice','$6.81',78);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (129,'L','100%','no ice','$8.99',150);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (130,'S','30%','light ice','$7.17',83);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (131,'S','0%','light ice','$5.89',161);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (132,'M','30%','no ice','$8.68',47);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (133,'S','30%','no ice','$7.92',99);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (134,'L','0%','no ice','$7.18',181);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (135,'S','70%','regular','$5.93',123);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (136,'L','70%','light ice','$8.21',128);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (137,'M','50%','light ice','$5.96',3);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (138,'L','70%','regular','$8.27',189);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (139,'S','0%','no ice','$6.67',10);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (140,'L','100%','no ice','$8.69',107);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (141,'S','70%','light ice','$5.33',160);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (142,'L','70%','regular','$5.48',149);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (143,'L','70%','light ice','$5.65',182);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (144,'S','0%','light ice','$6.33',89);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (145,'M','70%','regular','$6.88',21);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (146,'S','0%','no ice','$7.48',153);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (147,'L','100%','light ice','$8.93',158);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (148,'L','70%','regular','$8.33',88);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (149,'L','50%','light ice','$8.46',41);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (150,'M','70%','no ice','$8.27',134);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (151,'S','100%','regular','$5.46',3);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (152,'S','30%','no ice','$8.17',148);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (153,'M','100%','regular','$8.51',84);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (154,'S','70%','regular','$6.98',116);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (155,'L','100%','light ice','$7.27',22);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (156,'M','0%','light ice','$6.01',74);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (157,'M','50%','regular','$8.80',71);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (158,'M','0%','no ice','$7.32',48);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (159,'M','70%','regular','$6.89',88);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (160,'S','50%','regular','$7.61',192);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (161,'M','50%','no ice','$5.45',85);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (162,'S','70%','no ice','$5.35',121);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (163,'M','100%','light ice','$6.13',154);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (164,'M','30%','light ice','$7.48',80);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (165,'L','50%','light ice','$5.09',118);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (166,'L','100%','light ice','$6.74',9);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (167,'L','70%','no ice','$7.78',18);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (168,'S','30%','no ice','$5.74',63);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (169,'S','50%','regular','$6.70',150);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (170,'L','100%','no ice','$5.25',164);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (171,'M','100%','regular','$5.52',16);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (172,'S','30%','regular','$6.53',45);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (173,'S','30%','no ice','$7.84',109);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (174,'L','70%','regular','$7.37',91);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (175,'S','30%','no ice','$7.96',102);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (176,'L','0%','no ice','$5.55',175);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (177,'M','30%','no ice','$8.93',74);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (178,'S','100%','light ice','$5.24',155);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (179,'M','50%','light ice','$6.80',92);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (180,'M','0%','no ice','$8.21',45);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (181,'S','70%','light ice','$6.87',23);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (182,'S','100%','light ice','$5.35',94);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (183,'M','70%','light ice','$5.25',86);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (184,'M','100%','no ice','$8.48',171);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (185,'S','30%','light ice','$5.45',174);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (186,'S','50%','light ice','$5.86',123);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (187,'S','70%','regular','$8.82',139);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (188,'L','30%','regular','$6.89',125);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (189,'L','50%','no ice','$6.46',190);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (190,'M','0%','light ice','$5.80',16);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (191,'M','0%','light ice','$7.67',67);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (192,'L','70%','regular','$5.38',168);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (193,'L','0%','light ice','$6.22',24);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (194,'S','100%','regular','$7.90',197);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (195,'S','70%','no ice','$6.97',11);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (196,'L','50%','no ice','$8.82',60);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (197,'M','50%','light ice','$7.83',193);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (198,'L','100%','regular','$5.59',145);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (199,'M','0%','no ice','$6.71',32);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (200,'S','50%','light ice','$6.50',43);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (201,'M','0%','light ice','$5.69',154);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (202,'S','30%','regular','$7.87',189);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (203,'L','50%','light ice','$8.70',56);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (204,'L','100%','regular','$6.04',80);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (205,'M','50%','regular','$8.36',6);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (206,'S','50%','no ice','$6.91',45);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (207,'S','30%','regular','$5.68',48);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (208,'M','100%','regular','$8.80',70);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (209,'M','70%','light ice','$6.59',5);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (210,'L','70%','regular','$6.29',182);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (211,'S','50%','light ice','$6.30',33);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (212,'L','50%','regular','$8.30',158);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (213,'L','0%','regular','$8.26',134);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (214,'L','100%','regular','$8.81',149);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (215,'S','70%','light ice','$8.45',21);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (216,'M','30%','regular','$6.18',60);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (217,'M','30%','light ice','$5.04',124);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (218,'M','50%','light ice','$6.28',118);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (219,'M','0%','regular','$7.73',16);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (220,'L','0%','regular','$5.35',8);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (221,'M','50%','regular','$5.20',78);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (222,'S','50%','regular','$5.17',63);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (223,'S','30%','regular','$6.19',15);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (224,'S','50%','regular','$5.11',74);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (225,'M','50%','no ice','$8.24',71);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (226,'M','0%','no ice','$5.37',2);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (227,'L','50%','regular','$8.32',141);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (228,'L','50%','regular','$6.04',185);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (229,'L','50%','no ice','$5.58',133);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (230,'S','0%','regular','$5.52',171);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (231,'M','70%','light ice','$5.00',69);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (232,'L','50%','light ice','$6.53',9);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (233,'S','70%','no ice','$8.94',145);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (234,'S','100%','light ice','$6.26',26);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (235,'M','70%','regular','$8.52',34);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (236,'S','30%','light ice','$6.43',186);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (237,'S','50%','regular','$6.25',142);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (238,'M','50%','light ice','$7.02',79);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (239,'S','70%','regular','$5.70',57);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (240,'S','30%','no ice','$5.78',54);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (241,'M','70%','no ice','$6.22',194);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (242,'L','100%','light ice','$6.49',144);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (243,'L','100%','light ice','$7.76',43);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (244,'S','100%','no ice','$5.23',115);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (245,'S','70%','light ice','$5.61',99);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (246,'S','70%','regular','$6.82',111);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (247,'S','0%','light ice','$5.41',180);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (248,'S','100%','no ice','$7.49',76);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (249,'M','100%','regular','$8.78',196);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (250,'S','0%','no ice','$6.68',23);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (251,'L','30%','light ice','$7.10',41);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (252,'L','100%','light ice','$8.30',54);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (253,'L','30%','regular','$5.75',28);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (254,'M','100%','no ice','$6.94',149);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (255,'M','30%','regular','$5.53',16);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (256,'L','70%','no ice','$8.21',193);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (257,'M','30%','no ice','$7.25',69);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (258,'S','100%','no ice','$5.13',108);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (259,'L','50%','no ice','$7.44',179);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (260,'M','70%','light ice','$7.58',199);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (261,'M','100%','light ice','$6.26',30);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (262,'S','0%','light ice','$5.22',31);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (263,'M','30%','regular','$6.83',100);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (264,'M','70%','no ice','$7.92',180);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (265,'S','0%','no ice','$5.36',40);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (266,'L','0%','regular','$6.45',95);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (267,'L','100%','regular','$5.44',194);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (268,'M','100%','light ice','$7.44',137);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (269,'M','30%','no ice','$8.32',96);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (270,'M','50%','light ice','$6.96',196);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (271,'S','50%','regular','$8.42',154);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (272,'M','30%','no ice','$6.74',105);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (273,'M','50%','no ice','$6.83',114);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (274,'S','100%','light ice','$7.05',143);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (275,'S','0%','regular','$7.82',109);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (276,'L','30%','no ice','$5.06',18);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (277,'S','70%','regular','$6.90',112);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (278,'L','50%','regular','$5.27',41);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (279,'S','50%','no ice','$6.90',53);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (280,'L','50%','regular','$6.64',198);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (281,'L','70%','light ice','$6.55',80);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (282,'S','0%','light ice','$7.23',9);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (283,'L','100%','no ice','$5.22',106);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (284,'L','0%','regular','$6.08',71);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (285,'M','50%','no ice','$7.98',79);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (286,'S','100%','no ice','$5.29',159);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (287,'L','70%','light ice','$6.31',118);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (288,'S','100%','regular','$8.86',142);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (289,'M','0%','no ice','$8.61',185);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (290,'S','0%','light ice','$5.15',147);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (291,'S','70%','regular','$7.36',72);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (292,'M','30%','regular','$7.92',103);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (293,'S','0%','light ice','$8.79',29);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (294,'L','70%','regular','$7.59',125);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (295,'M','50%','regular','$8.49',100);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (296,'L','30%','regular','$7.02',183);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (297,'L','0%','no ice','$7.99',196);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (298,'M','50%','no ice','$6.97',111);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (299,'M','100%','light ice','$6.05',24);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (300,'S','50%','no ice','$7.16',54);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (301,'M','70%','light ice','$7.81',153);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (302,'S','30%','no ice','$5.92',197);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (303,'S','30%','regular','$7.44',73);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (304,'L','50%','no ice','$5.03',27);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (305,'L','70%','no ice','$5.23',16);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (306,'S','50%','regular','$8.90',82);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (307,'S','50%','light ice','$6.38',91);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (308,'M','70%','regular','$9.00',41);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (309,'S','30%','light ice','$6.59',17);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (310,'L','30%','no ice','$8.64',196);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (311,'M','0%','light ice','$6.98',130);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (312,'S','100%','no ice','$6.14',169);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (313,'S','0%','light ice','$6.03',143);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (314,'M','70%','no ice','$6.07',69);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (315,'L','50%','regular','$7.81',126);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (316,'L','30%','no ice','$8.42',115);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (317,'M','50%','no ice','$7.14',53);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (318,'M','100%','no ice','$6.39',97);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (319,'L','30%','light ice','$5.64',24);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (320,'S','50%','light ice','$6.97',124);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (321,'S','70%','light ice','$6.14',55);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (322,'M','50%','no ice','$7.32',194);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (323,'S','30%','regular','$5.20',25);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (324,'L','30%','light ice','$5.05',95);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (325,'S','0%','no ice','$7.24',15);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (326,'S','50%','regular','$5.27',59);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (327,'S','70%','no ice','$7.15',122);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (328,'L','0%','light ice','$5.20',66);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (329,'L','0%','no ice','$8.30',153);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (330,'S','70%','light ice','$5.97',181);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (331,'L','30%','light ice','$5.47',104);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (332,'L','70%','no ice','$6.01',163);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (333,'M','0%','no ice','$5.13',74);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (334,'M','0%','light ice','$8.81',22);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (335,'L','30%','no ice','$5.94',20);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (336,'L','30%','no ice','$7.75',123);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (337,'S','50%','no ice','$8.30',143);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (338,'S','100%','regular','$6.04',32);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (339,'M','100%','light ice','$7.10',133);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (340,'S','30%','regular','$7.93',29);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (341,'L','50%','no ice','$8.95',176);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (342,'L','50%','regular','$6.77',179);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (343,'M','50%','no ice','$8.63',174);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (344,'L','30%','regular','$8.49',134);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (345,'M','30%','regular','$6.61',164);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (346,'S','70%','regular','$7.93',35);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (347,'S','50%','no ice','$5.32',106);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (348,'L','70%','light ice','$5.72',107);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (349,'S','100%','regular','$8.98',120);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (350,'L','100%','regular','$8.04',189);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (351,'S','100%','light ice','$7.33',200);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (352,'M','50%','light ice','$6.00',114);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (353,'M','30%','regular','$8.81',178);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (354,'M','0%','no ice','$8.00',40);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (355,'L','50%','no ice','$7.22',52);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (356,'L','50%','regular','$5.94',72);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (357,'S','30%','no ice','$8.80',192);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (358,'S','100%','light ice','$6.07',191);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (359,'L','100%','light ice','$6.65',50);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (360,'M','100%','regular','$7.28',45);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (361,'L','50%','regular','$6.87',134);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (362,'L','30%','light ice','$5.64',37);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (363,'S','0%','no ice','$5.14',153);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (364,'L','70%','light ice','$8.61',53);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (365,'S','50%','no ice','$5.77',20);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (366,'M','70%','regular','$6.72',188);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (367,'S','50%','no ice','$5.28',43);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (368,'S','30%','regular','$5.62',69);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (369,'S','70%','light ice','$7.14',97);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (370,'S','50%','light ice','$6.99',171);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (371,'S','0%','no ice','$5.04',173);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (372,'L','50%','light ice','$6.94',21);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (373,'L','30%','no ice','$7.96',145);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (374,'S','0%','no ice','$7.17',48);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (375,'L','100%','regular','$5.58',123);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (376,'S','0%','light ice','$6.89',60);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (377,'L','100%','light ice','$8.96',128);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (378,'L','30%','no ice','$7.68',173);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (379,'M','50%','regular','$8.96',169);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (380,'L','50%','no ice','$6.39',80);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (381,'L','100%','light ice','$8.75',49);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (382,'L','50%','light ice','$7.51',119);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (383,'L','70%','no ice','$6.60',70);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (384,'L','100%','light ice','$5.05',73);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (385,'S','30%','no ice','$8.58',112);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (386,'L','50%','regular','$7.81',129);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (387,'L','50%','light ice','$7.29',95);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (388,'S','30%','no ice','$7.06',133);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (389,'M','100%','no ice','$6.65',130);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (390,'S','100%','light ice','$7.44',65);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (391,'S','100%','no ice','$6.57',10);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (392,'S','70%','light ice','$5.61',142);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (393,'M','0%','regular','$8.63',150);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (394,'S','0%','regular','$8.47',87);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (395,'M','100%','no ice','$6.67',71);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (396,'M','70%','light ice','$7.34',156);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (397,'M','0%','light ice','$6.26',127);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (398,'L','30%','regular','$7.90',188);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (399,'S','30%','regular','$6.90',117);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (400,'M','0%','no ice','$6.37',27);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (401,'M','100%','light ice','$6.52',185);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (402,'S','100%','light ice','$7.77',86);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (403,'S','30%','no ice','$8.68',70);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (404,'S','0%','no ice','$7.59',125);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (405,'M','70%','light ice','$7.26',49);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (406,'L','0%','no ice','$6.55',57);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (407,'M','0%','light ice','$5.36',56);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (408,'M','50%','no ice','$7.50',127);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (409,'S','50%','no ice','$8.59',54);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (410,'M','50%','no ice','$5.64',138);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (411,'L','30%','regular','$7.69',167);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (412,'M','70%','regular','$5.65',31);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (413,'S','0%','no ice','$8.27',87);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (414,'M','0%','no ice','$5.37',160);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (415,'M','100%','regular','$6.27',166);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (416,'L','50%','regular','$7.82',130);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (417,'M','70%','no ice','$8.40',175);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (418,'L','0%','light ice','$8.98',193);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (419,'S','30%','light ice','$5.49',197);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (420,'M','100%','no ice','$6.84',30);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (421,'M','30%','light ice','$7.15',173);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (422,'M','70%','regular','$5.01',157);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (423,'L','100%','light ice','$8.71',17);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (424,'L','0%','light ice','$7.78',176);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (425,'M','50%','no ice','$8.16',18);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (426,'S','0%','no ice','$5.79',174);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (427,'M','70%','light ice','$6.72',104);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (428,'M','0%','no ice','$8.12',24);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (429,'M','70%','regular','$6.41',95);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (430,'M','30%','light ice','$6.53',93);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (431,'L','70%','no ice','$5.46',39);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (432,'S','0%','regular','$7.00',152);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (433,'M','30%','light ice','$6.66',66);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (434,'S','70%','no ice','$8.48',132);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (435,'L','100%','light ice','$5.13',43);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (436,'M','100%','light ice','$5.03',190);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (437,'S','100%','light ice','$6.14',89);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (438,'S','70%','no ice','$8.14',1);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (439,'S','50%','light ice','$7.47',113);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (440,'M','100%','no ice','$5.02',40);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (441,'M','0%','regular','$6.35',83);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (442,'M','50%','no ice','$5.70',144);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (443,'M','70%','no ice','$5.09',131);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (444,'S','30%','no ice','$6.45',64);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (445,'S','50%','no ice','$7.86',151);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (446,'L','0%','light ice','$6.07',180);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (447,'L','70%','light ice','$6.29',134);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (448,'M','0%','light ice','$7.05',183);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (449,'M','0%','no ice','$8.48',88);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (450,'M','70%','regular','$6.34',49);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (451,'S','70%','light ice','$8.18',128);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (452,'M','70%','regular','$5.85',12);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (453,'S','0%','regular','$7.39',122);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (454,'S','50%','light ice','$5.83',146);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (455,'S','50%','no ice','$5.06',2);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (456,'L','100%','light ice','$5.70',159);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (457,'L','70%','regular','$6.56',129);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (458,'L','0%','no ice','$6.08',193);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (459,'S','30%','light ice','$8.43',141);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (460,'M','100%','regular','$8.94',182);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (461,'S','50%','regular','$8.23',45);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (462,'L','30%','light ice','$8.82',34);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (463,'M','100%','no ice','$7.29',188);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (464,'M','50%','regular','$5.61',174);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (465,'L','100%','light ice','$6.01',151);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (466,'M','100%','no ice','$8.30',152);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (467,'L','30%','no ice','$7.47',131);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (468,'S','0%','light ice','$5.42',186);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (469,'M','70%','light ice','$7.00',173);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (470,'L','100%','light ice','$7.32',83);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (471,'S','0%','regular','$5.34',105);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (472,'M','30%','regular','$5.90',104);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (473,'S','50%','regular','$8.71',32);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (474,'L','30%','no ice','$5.26',100);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (475,'M','0%','light ice','$7.60',149);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (476,'S','0%','no ice','$6.77',176);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (477,'M','30%','light ice','$6.09',117);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (478,'L','50%','no ice','$8.06',187);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (479,'M','100%','regular','$7.23',9);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (480,'L','100%','light ice','$6.07',89);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (481,'S','0%','regular','$6.01',169);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (482,'S','30%','regular','$6.45',43);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (483,'M','0%','light ice','$5.51',102);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (484,'S','50%','light ice','$8.40',16);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (485,'L','70%','no ice','$7.15',15);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (486,'S','30%','light ice','$6.04',119);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (487,'S','0%','regular','$7.35',28);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (488,'S','100%','regular','$5.96',191);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (489,'L','0%','no ice','$7.69',83);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (490,'M','100%','light ice','$5.84',87);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (491,'M','100%','light ice','$5.78',118);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (492,'S','50%','light ice','$5.43',174);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (493,'S','30%','regular','$8.56',155);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (494,'M','30%','regular','$6.26',166);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (495,'M','30%','no ice','$8.24',74);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (496,'S','70%','light ice','$6.24',46);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (497,'M','30%','no ice','$6.80',99);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (498,'S','0%','light ice','$6.94',22);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (499,'S','70%','no ice','$7.45',40);
INSERT INTO mytable(drink_id,size,sugar_lvl,ice_lvl,price,order_id) VALUES (500,'L','30%','regular','$8.55',27);
