CREATE TABLE IF NOT EXISTS mytable(
   ingredient_id   INTEGER  NOT NULL PRIMARY KEY 
  ,name            VARCHAR(20) NOT NULL
  ,quantity        INTEGER  NOT NULL
  ,expiration_date DATE  NOT NULL
);
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (1,'green tea',37,'4/26/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (2,'raw strawberry',71,'4/30/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (3,'honey',65,'4/29/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (4,'milk',68,'4/28/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (5,'black tea',66,'5/1/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (6,'tapioca',21,'4/25/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (7,'black tea',69,'4/27/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (8,'honey',84,'4/28/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (9,'cane sugar',100,'4/23/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (10,'raw pineapples',64,'5/2/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (11,'ube flavoring',79,'4/23/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (12,'cane sugar',49,'4/29/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (13,'cane sugar',27,'4/25/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (14,'ube flavoring',34,'4/21/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (15,'honey',60,'5/1/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (16,'green tea',62,'4/28/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (17,'raw pineapples',5,'4/29/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (18,'canned coconut juice',19,'4/26/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (19,'lychee tea',87,'4/29/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (20,'canned coconut juice',10,'5/2/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (21,'raw strawberry',69,'4/28/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (22,'raw pineapples',8,'4/26/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (23,'lychee tea',30,'4/27/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (24,'ube flavoring',11,'4/28/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (25,'ube flavoring',67,'4/27/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (26,'raw strawberry',7,'4/29/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (27,'milk',69,'4/22/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (28,'lychee tea',39,'4/28/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (29,'canned mango',21,'4/22/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (30,'tapioca',58,'4/21/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (31,'tapioca',62,'5/2/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (32,'raw strawberry',91,'4/30/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (33,'raw pineapples',32,'4/28/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (34,'green tea',49,'4/22/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (35,'green tea',36,'4/25/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (36,'raw strawberry',77,'4/28/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (37,'cane sugar',29,'4/22/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (38,'lychee tea',25,'4/30/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (39,'cane sugar',20,'4/30/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (40,'canned coconut juice',67,'4/27/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (41,'ube flavoring',87,'4/24/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (42,'milk',41,'4/29/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (43,'green tea',14,'4/26/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (44,'canned coconut juice',17,'4/27/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (45,'green tea',80,'4/26/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (46,'cane sugar',64,'4/25/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (47,'canned coconut juice',58,'4/28/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (48,'cane sugar',37,'5/2/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (49,'honey',56,'4/23/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (50,'raw pineapples',30,'4/26/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (51,'tapioca',17,'4/22/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (52,'tapioca',10,'4/26/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (53,'milk',73,'4/22/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (54,'tapioca',64,'4/27/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (55,'raw strawberry',91,'4/21/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (56,'canned coconut juice',87,'4/30/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (57,'cane sugar',11,'4/30/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (58,'raw strawberry',14,'4/25/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (59,'canned coconut juice',26,'4/25/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (60,'canned mango',73,'4/29/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (61,'lychee tea',48,'4/29/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (62,'canned mango',15,'4/21/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (63,'tapioca',98,'4/21/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (64,'black tea',44,'4/22/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (65,'honey',70,'5/2/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (66,'lychee tea',13,'5/1/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (67,'green tea',20,'4/22/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (68,'black tea',75,'4/27/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (69,'milk',22,'4/27/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (70,'raw strawberry',52,'4/26/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (71,'honey',9,'4/30/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (72,'canned coconut juice',12,'4/30/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (73,'ube flavoring',91,'4/25/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (74,'lychee tea',75,'4/21/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (75,'milk',70,'5/1/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (76,'milk',50,'4/30/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (77,'tapioca',64,'4/22/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (78,'honey',55,'4/23/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (79,'raw pineapples',55,'4/26/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (80,'canned mango',8,'4/26/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (81,'cane sugar',81,'4/27/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (82,'milk',57,'4/27/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (83,'ube flavoring',84,'4/25/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (84,'canned mango',92,'4/21/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (85,'raw pineapples',40,'5/2/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (86,'ube flavoring',17,'4/25/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (87,'honey',24,'4/25/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (88,'canned mango',58,'4/25/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (89,'ube flavoring',34,'4/22/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (90,'honey',97,'4/22/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (91,'lychee tea',19,'4/25/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (92,'raw pineapples',84,'4/21/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (93,'raw pineapples',55,'4/25/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (94,'black tea',43,'5/2/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (95,'lychee tea',62,'4/25/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (96,'raw pineapples',83,'4/29/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (97,'cane sugar',41,'5/2/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (98,'raw pineapples',98,'4/28/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (99,'black tea',58,'4/29/2023');
INSERT INTO mytable(ingredient_id,name,quantity,expiration_date) VALUES (100,'lychee tea',85,'4/26/2023');
